name: mlops-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python e ferramentas básicas
  - python=3.12
  - pip
  - git
  - curl

  # Pacotes científicos via conda (melhor performance)
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scikit-learn=1.7.0

  # Jupyter para desenvolvimento
  - jupyter
  - jupyterlab

  # Pacotes pip específicos
  - pip:
      - -r requirements.txt